name: base
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # provider: ^6.0.2
  google_fonts: 2.3.1
  flutter_svg: 1.0.3
  dio: 4.0.6
  rxdart: 0.27.3
  graphql: ^5.0.0
  # graphql_flutter: 5.0.1
  clipboard: 0.1.3
  encrypt: 5.0.1
  timeago: 3.2.2
  webview_flutter: 3.0.1
  cached_network_image: 3.2.0
  image_crop: 0.4.0
  file_picker: 4.5.1
  sqflite: ^2.0.2
  package_info: 2.0.2
  image_picker: 0.8.4+11
  flutter_image_compress: 1.1.0
  flutter_easyloading: 3.0.3
  mime_type: 1.0.0
  flutter_slidable: 0.6.0
  share: 2.0.4
  interactiveviewer_gallery: ^0.6.0
  badges: 2.0.2
  pull_to_refresh: 2.0.0
  firebase_database: ^9.0.18
  firebase_core: ^1.14.1
  firebase_analytics: ^8.0.0
  firebase_crashlytics: ^2.0.0

  get_it: ^7.2.0
  latlong2: ^0.8.1


  fluttertoast: 8.0.9
  shared_preferences: 2.0.13
  html: 0.15.0
  #cupertino_icons: 1.0.2
  intl: 0.17.0
  tuple: 2.0.0
  shimmer: 2.0.0
  crypto: 3.0.1
  url_launcher: 6.0.20
  #sliding_up_panel: 1.0.2
  logger: ^1.1.0
  uni_links: 0.5.1
  flutter_secure_storage: 4.2.0
  uuid: 3.0.6
  path_provider: 2.0.9
  device_info: 2.0.3
  loadmore: ^2.0.1
  flutter_native_image: ^0.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  artemis: ^7.1.0-beta.0
  build_runner: ^2.1.0
  freezed: ^0.14.2
  freezed_annotation: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
